# Database credentials
DB_NAME = "DBMercadologic"
DB_USER = "postgres"
DB_PASSWORD = "local"
DB_HOST = "localhost"
DB_PORT = "5432" # Porta padrão do PostgreSQL

# OpenAI API Key (Opcional, para a funcionalidade de IA)
OPENAI_API_KEY = "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"

# Google Gemini API Key
GEMINI_API_KEY = "AIzaSyDYY4Niu3BH8mc-MV8zfdeC8qRPz7Fp5A4"