# Database credentials
DB_NAME = "DBMercadologic"
DB_USER = "postgres"
DB_PASSWORD = "local"
DB_HOST = "localhost"
DB_PORT = "5432" # Porta padrão do PostgreSQL

# OpenAI API Key (Opcional, para a funcionalidade de IA)
OPENAI_API_KEY = ""

# Google Gemini API Key
GEMINI_API_KEY = "222"